[package]
name = "coding_compairson"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.14.0"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "traveling_salesman"
harness = false
